---
repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 5.0.0
    hooks:
      - id: buildifier
      - id: buildifier-lint

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v13.0.0'
    hooks:
      - id: clang-format
