---
repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 4.2.0.1
    hooks:
      - id: buildifier
      - id: buildifier-lint

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v10.0.1'
    hooks:
      - id: clang-format
