language: cpp
dist: bionic

addons:
  apt:
    packages: &common-apt-packages
      - python3-pip

matrix:
  include:
    - name: "bazel"
      addons: &gcc9
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      before_install: []
      install:
      - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.9.0/bazelisk-linux-amd64 --output-document=bazel
      before_script: []
      script:
      - |
        CC=gcc-9 CXX=g++-9 bazel \
          --output_base=$HOME/.cache/bazel \
          test \
          --config=gnulike \
          ...
