language: cpp
dist: xenial

matrix:
  include:
    - name: "gcc 7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script:
        - mkdir -p _build && cd _build
        - CXX=g++-7 cmake ..
        - make
        - ctest --output-on-failure

    - name: "gcc 7 coverage"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      before_install: pip install gcovr --user
      script:
        - mkdir -p _build && cd _build
        - CXX=g++-7 CXXFLAGS="-fprofile-arcs -ftest-coverage" cmake ..
        - make
        - ctest --output-on-failure
        - gcovr core/CMakeFiles/n_e_s_core.dir/src/ -p --root .. --fail-under-line=95

    - name: "clang 7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
      script:
        - mkdir -p _build && cd _build
        - CXX=clang++-7 cmake ..
        - make
        - ctest --output-on-failure

    - name: "clang-tidy"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - clang-tidy-7
            - libstdc++-7-dev
      script:
        - mkdir -p _build && cd _build
        - CXX=clang++-7 cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        - run-clang-tidy-7.py -q -p . "core|application"
