language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcovr
      script:
        - mkdir -p _build && cd _build
        - CXX=g++-7 CXXFLAGS="-fprofile-arcs -ftest-coverage" cmake ..
        - make
        - ctest --output-on-failure
        - gcovr core/CMakeFiles/n_e_s_core.dir/src/ -p --root ..

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
      script:
        - mkdir -p _build && cd _build
        - CXX=clang++-7 cmake ..
        - make
        - ctest --output-on-failure

install:
  - mkdir -p cmake-3.12
  - wget -qO- "https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz" \
    | tar --strip-components=1 -xz -C cmake-3.12
  - export PATH=`pwd`/cmake-3.12/bin:$PATH
