language: cpp
dist: bionic

addons:
  apt:
    packages: &common-apt-packages
      - python3-pip

matrix:
  include:
    - name: "bazel"
      addons: &gcc9
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      before_install:
        - OS=linux
        - ARCH=x86_64
        - V=2.1.1
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
        - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
        - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
        - URL="$GH_BASE/$GH_ARTIFACT"
        - wget -O install.sh $URL
        - chmod +x install.sh
        - ./install.sh --user
        - rm -f install.sh
      install: []
      before_script: []
      script:
      - |
        CC=gcc-9 CXX=g++-9 bazel \
          --output_base=$HOME/.cache/bazel \
          test \
          --config=gnulike \
          ...

    - name: "clang-tidy 9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *common-apt-packages
            - clang-9
            - clang-tidy-9
            - libstdc++-8-dev
      script:
        - CXX=clang++-9 cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        - travis_wait run-clang-tidy-9.py -q -p . "application|core|nes" -header-filter="(nes|core)/"

install:
  - python3 -m pip install pip==20.2.1 --upgrade
  - python3 -m pip install cmake==3.18.0 ninja==1.10.0.post1 --upgrade --user

before_script:
  - cmake --version
  - ninja --version
  - mkdir _build && cd _build
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" $CMAKE_EXTRA_OPTIONS ..
  - cmake --build . --parallel 2
  - ctest --output-on-failure
