shallow_clone: true

configuration:
  - Debug
  - Release

environment:
  matrix:
  - GENERATOR: Visual Studio 15 2017
  - GENERATOR: Visual Studio 15 2017 Win64

image:
  - Visual Studio 2017

cache:
  - C:\cmake-3.13.0-win32-x86

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.13.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.13/cmake-3.13.0-win32-x86.zip'
        7z x -y cmake-3.13.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.13.0-win32-x86\bin;$env:PATH"

before_build:
  - cmd: flags.bat
  - ps: |
      mkdir build
      cd build

      echo generator="$env:GENERATOR"
      cmake .. -G"$env:GENERATOR"

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure
