name: Linux CI

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-18.04-gcc-9
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
            configuration: Debug

          - name: ubuntu-18.04-gcc-9-coverage
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
            configuration: Debug
            coverage: true
            cmake-args: -DENABLE_COVERAGE=ON

          - name: ubuntu-18.04-gcc-10
            os: ubuntu-18.04
            compiler: gcc
            version: "10"
            configuration: Debug

          - name: ubuntu-18.04-clang-8
            os: ubuntu-18.04
            compiler: clang
            version: "8"
            configuration: Debug

          - name: ubuntu-18.04-clang-9-sanitizers
            os: ubuntu-18.04
            compiler: clang
            version: "9"
            configuration: Debug
            cmake-args: -DADDRESS_SANITIZER=ON -DUNDEFINED_SANITIZER=ON

          - name: ubuntu-18.04-clang-10-sanitizers
            os: ubuntu-18.04
            compiler: clang
            version: "10"
            configuration: Debug
            cmake-args: -DADDRESS_SANITIZER=ON -DUNDEFINED_SANITIZER=ON

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          echo "::add-path::/home/runner/.local/bin"
          python3 -m pip install pip --upgrade
          python3 -m pip install cmake==3.14.4 ninja==1.9.0.post1 --upgrade

          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main' -y
          sudo apt update

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
            echo "::set-env name=CC::gcc-${{ matrix.version }}"
            echo "::set-env name=CXX::g++-${{ matrix.version }}"
          else
            sudo apt-get install -y clang-${{ matrix.version }} g++-multilib
            echo "::set-env name=CC::clang-${{ matrix.version }}"
            echo "::set-env name=CXX::clang++-${{ matrix.version }}"
          fi

      - name: CMake
        run: |
          cmake --version
          ninja --version
          echo "CMake args: ${{ matrix.cmake-args }}"

          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ${{ matrix.cmake-args }}

      - name: Build
        run: |
          cmake --build build

      - name: Test
        env:
          ASAN_OPTIONS: "symbolize=1:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1"
          UBSAN_OPTIONS: "print_stacktrace=1:halt_on_error=1"
        run: |
          (cd build && ctest -C ${{ matrix.configuration }} )

      - name: Coverage
        if: matrix.coverage
        run: |
          python3 -m pip install gcovr
          (cd build && gcovr --gcov-executable gcov-9 -p --root .. --fail-under-line=94 --exclude 'CMakeFiles/' --exclude '_deps/' --exclude '(.+/)?test/' --exclude '.+/(application|nestest)/')
